thermostat_house:  # Params for thermostat_house
  ros__parameters:
    thermostat_name: 'thermostat'
    target_temperature: 30
thermostat_kitchen:  # Params for thermostat_kitchen
  ros__parameters:
    thermostat_name: 'kitchen'
    target_temperature: 12
thermostat_livingroom:  # Params for thermostat_livingroom
  ros__parameters:
    thermostat_name: 'livingroom'
    target_temperature: 14
thermostat_bedroom:  # Params for thermostat_bedroom
  ros__parameters:
    thermostat_name: 'bedroom'
    target_temperature: 15